### ISSUE TITLE
Try choo-audio?

### ISSUE THREAD

**Issue by YerkoPalma** [joshwnj/choonz#3]
Hi :wave: 
Nice project, may I suggest to try [choo-audio](https://github.com/YerkoPalma/choo-audio)? It seems to be a perfect fit for your use case. 

Let me know what you think :)

**Comment by joshwnj** [comment]
Hey, thanks.  I've actually just rewritten part of this app to use the `Audio` object instead of webaudio: https://github.com/joshwnj/choonz/pull/2/files

I found that while it's possible to do with webaudio, I found [several reasons](https://github.com/joshwnj/choonz/issues/1) why `Audio` is a much better fit.

`choo-audio` looks really cool, I'd like to try that out some time.
